theme: jekyll-theme-minimal

title: Fernando Pradas
description: Senior Backend Engineer

logo: https://github.com/letnando/website/raw/master/profile.jpg


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
