theme: jekyll-theme-minimal

title: Fernando Pradas
description: Senior Backend Engineer

logo: https://media.licdn.com/dms/image/C5603AQHWApnTdDUkFg/profile-displayphoto-shrink_200_200/0?e=1577318400&v=beta&t=pl3AXbS7LTKgt4hOUixsb9HXiID4ppC6_wJBIiW4pzA


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
