theme: jekyll-theme-minimal

title: Fernando Pradas
description: Senior Backend Engineer

logo: https://pbs.twimg.com/profile_images/1204863819681533953/vuiQP6pV.jpg


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
