theme: jekyll-theme-minimal

title: Fernando Pradas
description: Senior Backend Engineer

logo: https://media-exp1.licdn.com/dms/image/C5103AQETMryZTLWFfA/profile-displayphoto-shrink_200_200/0?e=1587600000&v=beta&t=W-cigN2EE48_SVsBWZAo_r9N73dgMkTM76zOOB6yR_U


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
